apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: payment-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: payment-processor/gateway:local
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_ADDR
              value: ":8080"
            - name: LEDGER_GRPC_ADDR
              value: ledger:9001
            - name: KAFKA_BROKER
              value: redpanda:9092
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: payment-processor
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
