version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8090:8080"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1


