apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: payment-processor
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:v24.2.7
          args:
            - redpanda
            - start
            - --smp=1
            - --memory=512M
            - --overprovisioned
            - --kafka-addr=internal://0.0.0.0:9092
            - --advertise-kafka-addr=internal://redpanda:9092
          ports:
            - containerPort: 9092
          readinessProbe:
            exec:
              command: ["rpk", "cluster", "health", "--exit-when-healthy"]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: payment-processor
spec:
  selector:
    app: redpanda
  ports:
    - port: 9092
